name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: mkdir sample
      - run: ls -al
      - run: pwd
      - run: cp sample.py ./sample
      - run: cd sample
      - run: python sample.py
      - run: echo "Hello World!"
      
